Linted
adafruit/Adafruit_CircuitPython_USB_Host_Mass_Storage pull request #1
Opened 2023-08-03 21:49 UTC by tannewt

2023-08-03 21:51 UTC, tannewt commented
Depends on https://github.com/adafruit/Adafruit_CircuitPython_USB_Host_Descriptors/pull/1

2023-08-09 18:21 UTC, jepler approved these changes
the computer eats the lint so we don't have to

2023-08-09 18:41 UTC, dhalbert requested changes
Looks fine -- just some typos.

2023-08-09 18:41 UTC, dhalbert commented on adafruit_usb_host_mass_storage.py
> +    """CircuitPython BlockDevice backed by a USB mass storage device (aka thumb drive.)"""
```suggestion
    """CircuitPython BlockDevice backed by a USB mass storage device (aka thumb drive)."""
```

2023-08-09 18:41 UTC, dhalbert commented on README.rst
> +* `Adafruit CircuitPython 9+ <https://github.com/adafruit/circuitpython>`_
Not sure where the `9+` came from.
```suggestion
* `Adafruit CircuitPython <https://github.com/adafruit/circuitpython>`_
```

2023-08-09 18:42 UTC, dhalbert commented on README.rst
> +* `Adafruit CircuitPython 9+ <https://github.com/adafruit/circuitpython>`_
Aha, do you mean 9.0.0? I get it. Maybe say `9.0.0 and later`

2023-08-15 17:53 UTC, tannewt commented
Still waiting for you @dhalbert

2023-08-15 19:01 UTC, dhalbert commented
> Still waiting for you @dhalbert

Sorry! I did not see the re-review request.

2023-08-15 19:01 UTC, merged